import { Link, createFileRoute } from "@tanstack/react-router";
import { CalendarDays, CheckCircle2, Circle, Clock3, FileText, Settings2, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { StatusPill } from "@/components/status-pill";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { bookById, phases } from "@/lib/book-data";

export const Route = createFileRoute("/books/$bookId/")({
  head: () => ({ meta: [
    { title: "Book Overview — Book Cycles" }, { name: "description", content: "See the phases, milestones, collaborators, and next actions for your book." },
    { property: "og:title", content: "Book Overview — Book Cycles" }, { property: "og:description", content: "See the phases, milestones, collaborators, and next actions for your book." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: BookOverview,
});

function BookOverview() {
  const { bookId } = Route.useParams(); const book = bookById(bookId);
  return <AppShell><header className="mb-8 flex flex-col gap-6 border-b border-border pb-7 md:flex-row md:items-end md:justify-between"><div className="flex gap-5"><img src={book.cover} alt={`Cover artwork for ${book.title}`} width={768} height={1152} className="aspect-[2/3] w-20 object-cover shadow-sm" /><div><div className="mb-2 flex flex-wrap gap-2"><StatusPill tone="good">{book.status}</StatusPill><StatusPill>{book.genre}</StatusPill></div><h1 className="font-serif text-4xl font-semibold md:text-5xl">{book.title}</h1><p className="mt-1 text-muted-foreground">by {book.author}</p></div></div><div className="flex gap-2"><Button variant="outline" asChild><Link to="/books/$bookId/details" params={{ bookId }}><Settings2 />Book details</Link></Button><Button variant="outline" asChild><Link to="/books/$bookId/reflection" params={{ bookId }}><FileText />Reflection</Link></Button></div></header>
    <section className="mb-10 grid gap-6 border-b border-border pb-8 md:grid-cols-[1fr_2fr]"><div><p className="text-sm text-muted-foreground">Overall progress</p><p className="mt-1 font-serif text-4xl font-semibold">{book.progress}%</p><Progress value={book.progress} className="mt-3" /></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3"><div><CalendarDays className="mb-2 size-4 text-primary"/><p className="text-xs text-muted-foreground">Target publication</p><p className="font-semibold">{book.target}</p></div><div><Clock3 className="mb-2 size-4 text-primary"/><p className="text-xs text-muted-foreground">Next action</p><p className="font-semibold">24 June</p></div><div><Users className="mb-2 size-4 text-primary"/><p className="text-xs text-muted-foreground">Team</p><p className="font-semibold">3 collaborators</p></div></div></section>
    <section><div className="mb-5 flex items-end justify-between"><div><h2 className="font-serif text-3xl font-semibold">Your publishing path</h2><p className="mt-1 text-sm text-muted-foreground">Six phases from private manuscript to published book.</p></div></div><div className="relative space-y-5 before:absolute before:bottom-8 before:left-5 before:top-7 before:w-px before:bg-border">{phases.map((phase, index) => <article key={phase.id} className="relative grid grid-cols-[42px_1fr] gap-4"><span className={`z-10 grid size-10 place-items-center rounded-full border-2 font-semibold ${index < 1 ? "border-primary bg-primary text-primary-foreground" : index === 1 ? "border-primary bg-background text-primary" : "border-border bg-background text-muted-foreground"}`}>{index + 1}</span><div className="border bg-card p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-serif text-2xl font-semibold">{phase.name}</h3><StatusPill tone={phase.name === "Launch" ? "warm" : "neutral"}>{phase.mode}</StatusPill></div><p className="mt-1 text-sm text-muted-foreground">{phase.summary}</p></div><span className="text-sm text-muted-foreground">{phase.milestones.filter((m) => m.status === "Complete").length}/{phase.milestones.length} complete</span></div><div className="mt-4 divide-y divide-border border-t border-border">{phase.milestones.map((milestone) => <Link key={milestone.id} to="/books/$bookId/milestones/$milestoneId" params={{ bookId, milestoneId: milestone.id }} className="flex items-center gap-3 py-3 text-sm hover:text-primary">{milestone.status === "Complete" ? <CheckCircle2 className="size-5 text-primary" /> : <Circle className="size-5 text-muted-foreground" />}<span className="flex-1 font-medium">{milestone.name}</span>{milestone.due && <span className="text-muted-foreground">{milestone.due}</span>}</Link>)}</div></div></article>)}</div></section>
  </AppShell>;
}
