import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { bookById } from "@/lib/book-data";

export const Route = createFileRoute("/books/$bookId/details")({ head: () => ({ meta: [
  { title: "Book Details — Book Cycles" }, { name: "description", content: "Edit the publishing, audience, format, and distribution details for your book." }, { property: "og:title", content: "Book Details — Book Cycles" }, { property: "og:description", content: "Edit the publishing, audience, format, and distribution details for your book." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: BookDetails });

const Field = ({ label, value = "" }: { label: string; value?: string | undefined }) => <label className="block text-sm font-semibold">{label}<Input className="mt-2" defaultValue={value}/></label>;
function BookDetails() { const { bookId } = Route.useParams(); const book = bookById(bookId); return <AppShell><PageHeading title="Book Details" description="The working record behind your publishing plan." action={<Button>Save changes</Button>} /><form className="space-y-10"><section><h2 className="mb-5 font-serif text-2xl font-semibold">Book identity</h2><div className="grid gap-5 md:grid-cols-2"><Field label="Working title" value={book.title}/><Field label="Subtitle" value={book.subtitle}/><Field label="Author or pen name" value={book.author}/><Field label="Genre or category" value={book.genre}/><Field label="Series"/><Field label="Edition" value="First edition"/></div></section><section className="border-t border-border pt-8"><h2 className="mb-5 font-serif text-2xl font-semibold">Audience and goals</h2><div className="grid gap-5 md:grid-cols-2"><Field label="Primary audience" value="Adult readers of literary family sagas"/><Field label="Secondary audience" value="Readers of coastal and place-based fiction"/><Field label="Comparable title 1" value="The Dutch House"/><Field label="Comparable title 2" value="The Paper Palace"/><label className="block text-sm font-semibold md:col-span-2">Book goals<Textarea className="mt-2" defaultValue="Publish a beautifully produced debut and build a lasting reader list."/></label></div></section><section className="border-t border-border pt-8"><h2 className="mb-5 font-serif text-2xl font-semibold">Production</h2><div className="grid gap-5 md:grid-cols-3"><Field label="Formats" value="Paperback, ebook"/><Field label="Length estimate" value="82,000 words"/><Field label="Language" value="English"/><Field label="Trim size" value="5.5 × 8.5 in"/><Field label="Bleed" value="No bleed"/><Field label="Paper type" value="Cream, 70 gsm"/><Field label="ISBN"/><Field label="Imprint" value="Low Tide Books"/><Field label="List price" value="$17.99"/></div></section><section className="border-t border-border pt-8"><h2 className="mb-5 font-serif text-2xl font-semibold">Publishing plan</h2><div className="grid gap-5 md:grid-cols-2"><Field label="Publishing path" value="Independent publishing"/><Field label="Target publication date" value="18 September 2026"/><Field label="Budget" value="$3,500"/><Field label="Distribution channels" value="KDP, IngramSpark, direct"/><Field label="Metadata bundle" value="Working draft"/><Field label="Linked Book Cycles" value="None"/></div></section></form></AppShell>; }
