import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, PartyPopper } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/books/$bookId/reflection")({ head: () => ({ meta: [
  { title: "Post-Launch Reflection — Book Cycles" }, { name: "description", content: "Reflect on your book launch and decide what comes next." }, { property: "og:title", content: "Post-Launch Reflection — Book Cycles" }, { property: "og:description", content: "Reflect on your book launch and decide what comes next." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Reflection });
function Reflection() { const [achieved, setAchieved] = useState<"yes"|"no">("yes"); const [saved, setSaved] = useState(false); return <AppShell><div className="mb-8 rounded-2xl border border-accent/50 bg-accent/20 p-6 shadow-xs md:p-8"><PartyPopper className="mb-4 size-7 text-chart-1"/><p className="font-serif text-3xl font-normal">You made a book.</p><p className="mt-2 max-w-2xl text-muted-foreground">Take a quiet moment to mark what happened before you decide what comes next.</p></div><PageHeading title="Post-Launch Reflection" description="Your answers stay with this book cycle."/><div className="max-w-3xl space-y-5"><section className="rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 className="text-lg font-semibold">Did this book achieve its goals?</h2><div className="mt-3 flex gap-2">{(["yes","no"] as const).map((value) => <Button key={value} type="button" variant={achieved === value ? "default" : "outline"} onClick={() => setAchieved(value)} className="min-w-24 capitalize">{value}</Button>)}</div><Textarea className="mt-3 min-h-28" placeholder="What tells you that?"/></section>{achieved === "no" && <section className="rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 className="text-lg font-semibold">Was the book published on or before its target date?</h2><div className="mt-3 flex gap-2"><Button type="button" variant="outline">Yes</Button><Button type="button">No</Button></div></section>}<section className="rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 className="text-lg font-semibold">What are the next steps for this book to be successful?</h2><Textarea className="mt-3 min-h-36" placeholder="Consider reader outreach, reviews, backlist links, or your next book."/></section><section className="rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 className="text-lg font-semibold">What do you want to remember for your next book? <span className="font-normal text-muted-foreground">Optional</span></h2><Textarea className="mt-3 min-h-28"/></section><Button onClick={() => setSaved(true)} className={cn(saved && "bg-secondary text-secondary-foreground")} >{saved && <CheckCircle2/>}{saved ? "Reflection saved" : "Save reflection"}</Button></div></AppShell>; }
