import { Link, createFileRoute } from "@tanstack/react-router";
import { Check, Feather, Palette, Sparkles } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { Button } from "@/components/ui/button";
import foxCover from "@/assets/fox-lantern-cover.jpg";
import riverCover from "@/assets/river-map-cover.jpg";

export const Route = createFileRoute("/templates")({ head: () => ({ meta: [
  { title: "Book Cycle Templates — Book Cycles" }, { name: "description", content: "Start with a genre-aware publishing plan and tailor it to your book." }, { property: "og:title", content: "Book Cycle Templates — Book Cycles" }, { property: "og:description", content: "Start with a genre-aware publishing plan and tailor it to your book." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Templates });
function Templates() { return <AppShell><PageHeading title="Book Cycle Templates" description="A strong starting path, built for how your kind of book is actually made."/><div className="grid gap-6 lg:grid-cols-2"><article className="grid overflow-hidden border bg-card sm:grid-cols-[180px_1fr]"><img src={foxCover} alt="Fox carrying a lantern through a painted garden" width={768} height={1152} className="h-full min-h-64 w-full object-cover"/><div className="p-6"><div className="mb-3 flex flex-wrap gap-2"><StatusPill tone="warm">Children’s picture book</StatusPill><StatusPill>6 phases</StatusPill></div><h2 className="font-serif text-3xl font-semibold">Picture Book Path</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">For illustrated books where words, art, and page turns need to develop together.</p><ul className="mt-5 space-y-2 text-sm"><li className="flex gap-2"><Check className="size-4 text-primary"/>Mandatory illustrator track</li><li className="flex gap-2"><Check className="size-4 text-primary"/>Parallel layout and artwork approvals</li><li className="flex gap-2"><Check className="size-4 text-primary"/>Print-proof color check</li></ul><Button className="mt-6" asChild><Link to="/books/new">Use this template</Link></Button></div></article><article className="grid overflow-hidden border bg-card sm:grid-cols-[180px_1fr]"><img src={riverCover} alt="Abstract river map artwork" width={768} height={1152} className="h-full min-h-64 w-full object-cover" loading="lazy"/><div className="p-6"><div className="mb-3 flex flex-wrap gap-2"><StatusPill tone="good">Fiction & memoir</StatusPill><StatusPill>6 phases</StatusPill></div><h2 className="font-serif text-3xl font-semibold">Longform Author Path</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A complete editorial and production journey for prose-led books.</p><ul className="mt-5 space-y-2 text-sm"><li className="flex gap-2"><Feather className="size-4 text-primary"/>Layered revision loops</li><li className="flex gap-2"><Palette className="size-4 text-primary"/>Cover and interior production tracks</li><li className="flex gap-2"><Sparkles className="size-4 text-primary"/>Budget-aware Book Coach guidance</li></ul><Button className="mt-6" variant="outline" asChild><Link to="/books/new">Use this template</Link></Button></div></article></div></AppShell>; }