/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCollaborationsRouteImport } from './routes/_authenticated/collaborations'
import { Route as AuthenticatedCyclesRouteImport } from './routes/_authenticated/cycles'
import { Route as AuthenticatedMyTableRouteImport } from './routes/_authenticated/my-table'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as ApiCoachPlanRouteImport } from './routes/api/coach-plan'
import { Route as ApiPenRouteImport } from './routes/api/pen'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ShelfSlugRouteImport } from './routes/shelf.$slug'
import { Route as TableIndexRouteImport } from './routes/table.index'
import { Route as TableIssueIdRouteImport } from './routes/table.$issueId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin.issues'
import { Route as AuthenticatedAdminMissionpageRouteImport } from './routes/_authenticated/admin.missionpage'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminReleasesRouteImport } from './routes/_authenticated/admin.releases'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminSitewordsRouteImport } from './routes/_authenticated/admin.sitewords'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminTablehomeRouteImport } from './routes/_authenticated/admin.tablehome'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'
import { Route as AuthenticatedBooksAddRouteImport } from './routes/_authenticated/books.add'
import { Route as AuthenticatedBooksNewRouteImport } from './routes/_authenticated/books.new'
import { Route as AuthenticatedHelpIndexRouteImport } from './routes/_authenticated/help.index'
import { Route as AuthenticatedHelpReleasesRouteImport } from './routes/_authenticated/help.releases'
import { Route as AuthenticatedHelpSupportRouteImport } from './routes/_authenticated/help.support'
import { Route as AuthenticatedPenIndexRouteImport } from './routes/_authenticated/pen.index'
import { Route as AuthenticatedPenThreadIdRouteImport } from './routes/_authenticated/pen.$threadId'
import { Route as AuthenticatedPenButtonsRouteImport } from './routes/_authenticated/pen.buttons'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates.$templateId'
import { Route as TableIssueIdFlyerRouteImport } from './routes/table.$issueId_.flyer'
import { Route as TableAuthorsAuthorIdRouteImport } from './routes/table.authors.$authorId'
import { Route as TableBooksBookIdRouteImport } from './routes/table.books.$bookId'
import { Route as AuthenticatedAdminHelpIndexRouteImport } from './routes/_authenticated/admin.help.index'
import { Route as AuthenticatedAdminHelpArticleIdRouteImport } from './routes/_authenticated/admin.help.$articleId'
import { Route as AuthenticatedAdminJournalIndexRouteImport } from './routes/_authenticated/admin.journal.index'
import { Route as AuthenticatedAdminJournalPostIdRouteImport } from './routes/_authenticated/admin.journal.$postId'
import { Route as AuthenticatedBooksBookIdIndexRouteImport } from './routes/_authenticated/books.$bookId.index'
import { Route as AuthenticatedBooksBookIdDetailsRouteImport } from './routes/_authenticated/books.$bookId.details'
import { Route as AuthenticatedBooksBookIdReflectionRouteImport } from './routes/_authenticated/books.$bookId.reflection'
import { Route as AuthenticatedBooksBookIdTeamRouteImport } from './routes/_authenticated/books.$bookId.team'
import { Route as AuthenticatedHelpArticlesSlugRouteImport } from './routes/_authenticated/help.articles.$slug'
import { Route as AuthenticatedHelpCategoriesCategorySlugRouteImport } from './routes/_authenticated/help.categories.$categorySlug'
import { Route as AuthenticatedHelpRequestsIndexRouteImport } from './routes/_authenticated/help.requests.index'
import { Route as AuthenticatedHelpRequestsRequestIdRouteImport } from './routes/_authenticated/help.requests.$requestId'
import { Route as AuthenticatedTemplatesMineTemplateIdRouteImport } from './routes/_authenticated/templates.mine.$templateId'
import { Route as ApiPublicShelfImageSlugRouteImport } from './routes/api/public/shelf-image.$slug'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport } from './routes/_authenticated/books.$bookId.milestones.$milestoneId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollaborationsRoute =
  AuthenticatedCollaborationsRouteImport.update({
    id: '/collaborations',
    path: '/collaborations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCyclesRoute = AuthenticatedCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTableRoute = AuthenticatedMyTableRouteImport.update({
  id: '/my-table',
  path: '/my-table',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCoachPlanRoute = ApiCoachPlanRouteImport.update({
  id: '/api/coach-plan',
  path: '/api/coach-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPenRoute = ApiPenRouteImport.update({
  id: '/api/pen',
  path: '/api/pen',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfSlugRoute = ShelfSlugRouteImport.update({
  id: '/shelf/$slug',
  path: '/shelf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIssueIdRoute = TableIssueIdRouteImport.update({
  id: '/table/$issueId',
  path: '/table/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMissionpageRoute =
  AuthenticatedAdminMissionpageRouteImport.update({
    id: '/missionpage',
    path: '/missionpage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReleasesRoute =
  AuthenticatedAdminReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSitewordsRoute =
  AuthenticatedAdminSitewordsRouteImport.update({
    id: '/sitewords',
    path: '/sitewords',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTablehomeRoute =
  AuthenticatedAdminTablehomeRouteImport.update({
    id: '/tablehome',
    path: '/tablehome',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksAddRoute = AuthenticatedBooksAddRouteImport.update({
  id: '/books/add',
  path: '/books/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksNewRoute = AuthenticatedBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpIndexRoute = AuthenticatedHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpReleasesRoute =
  AuthenticatedHelpReleasesRouteImport.update({
    id: '/help/releases',
    path: '/help/releases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpSupportRoute =
  AuthenticatedHelpSupportRouteImport.update({
    id: '/help/support',
    path: '/help/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenIndexRoute = AuthenticatedPenIndexRouteImport.update({
  id: '/pen/',
  path: '/pen/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenThreadIdRoute =
  AuthenticatedPenThreadIdRouteImport.update({
    id: '/pen/$threadId',
    path: '/pen/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenButtonsRoute = AuthenticatedPenButtonsRouteImport.update({
  id: '/pen/buttons',
  path: '/pen/buttons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TableIssueIdFlyerRoute = TableIssueIdFlyerRouteImport.update({
  id: '/table/$issueId_/flyer',
  path: '/table/$issueId/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const TableAuthorsAuthorIdRoute = TableAuthorsAuthorIdRouteImport.update({
  id: '/table/authors/$authorId',
  path: '/table/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableBooksBookIdRoute = TableBooksBookIdRouteImport.update({
  id: '/table/books/$bookId',
  path: '/table/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminHelpIndexRoute =
  AuthenticatedAdminHelpIndexRouteImport.update({
    id: '/help/',
    path: '/help/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHelpArticleIdRoute =
  AuthenticatedAdminHelpArticleIdRouteImport.update({
    id: '/help/$articleId',
    path: '/help/$articleId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalIndexRoute =
  AuthenticatedAdminJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalPostIdRoute =
  AuthenticatedAdminJournalPostIdRouteImport.update({
    id: '/journal/$postId',
    path: '/journal/$postId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBooksBookIdIndexRoute =
  AuthenticatedBooksBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdDetailsRoute =
  AuthenticatedBooksBookIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdReflectionRoute =
  AuthenticatedBooksBookIdReflectionRouteImport.update({
    id: '/reflection',
    path: '/reflection',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdTeamRoute =
  AuthenticatedBooksBookIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedHelpArticlesSlugRoute =
  AuthenticatedHelpArticlesSlugRouteImport.update({
    id: '/help/articles/$slug',
    path: '/help/articles/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCategoriesCategorySlugRoute =
  AuthenticatedHelpCategoriesCategorySlugRouteImport.update({
    id: '/help/categories/$categorySlug',
    path: '/help/categories/$categorySlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRequestsIndexRoute =
  AuthenticatedHelpRequestsIndexRouteImport.update({
    id: '/help/requests/',
    path: '/help/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRequestsRequestIdRoute =
  AuthenticatedHelpRequestsRequestIdRouteImport.update({
    id: '/help/requests/$requestId',
    path: '/help/requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesMineTemplateIdRoute =
  AuthenticatedTemplatesMineTemplateIdRouteImport.update({
    id: '/templates/mine/$templateId',
    path: '/templates/mine/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicShelfImageSlugRoute = ApiPublicShelfImageSlugRouteImport.update({
  id: '/api/public/shelf-image/$slug',
  path: '/api/public/shelf-image/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBooksBookIdMilestonesMilestoneIdRoute =
  AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/collaborations': typeof AuthenticatedCollaborationsRoute
  '/cycles': typeof AuthenticatedCyclesRoute
  '/my-table': typeof AuthenticatedMyTableRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/api/pen': typeof ApiPenRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shelf/$slug': typeof ShelfSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/issues/': typeof IssuesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/table/': typeof TableIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/missionpage': typeof AuthenticatedAdminMissionpageRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/sitewords': typeof AuthenticatedAdminSitewordsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tablehome': typeof AuthenticatedAdminTablehomeRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRouteWithChildren
  '/books/add': typeof AuthenticatedBooksAddRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/help/releases': typeof AuthenticatedHelpReleasesRoute
  '/help/support': typeof AuthenticatedHelpSupportRoute
  '/pen/$threadId': typeof AuthenticatedPenThreadIdRoute
  '/pen/buttons': typeof AuthenticatedPenButtonsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/$issueId/flyer': typeof TableIssueIdFlyerRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/help/': typeof AuthenticatedHelpIndexRoute
  '/pen/': typeof AuthenticatedPenIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/admin/help/$articleId': typeof AuthenticatedAdminHelpArticleIdRoute
  '/admin/journal/$postId': typeof AuthenticatedAdminJournalPostIdRoute
  '/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/help/articles/$slug': typeof AuthenticatedHelpArticlesSlugRoute
  '/help/categories/$categorySlug': typeof AuthenticatedHelpCategoriesCategorySlugRoute
  '/help/requests/$requestId': typeof AuthenticatedHelpRequestsRequestIdRoute
  '/templates/mine/$templateId': typeof AuthenticatedTemplatesMineTemplateIdRoute
  '/api/public/shelf-image/$slug': typeof ApiPublicShelfImageSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/help/': typeof AuthenticatedAdminHelpIndexRoute
  '/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
  '/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/help/requests/': typeof AuthenticatedHelpRequestsIndexRoute
  '/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/collaborations': typeof AuthenticatedCollaborationsRoute
  '/cycles': typeof AuthenticatedCyclesRoute
  '/my-table': typeof AuthenticatedMyTableRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/api/pen': typeof ApiPenRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shelf/$slug': typeof ShelfSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/table': typeof TableIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/missionpage': typeof AuthenticatedAdminMissionpageRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/sitewords': typeof AuthenticatedAdminSitewordsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tablehome': typeof AuthenticatedAdminTablehomeRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/books/add': typeof AuthenticatedBooksAddRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/help/releases': typeof AuthenticatedHelpReleasesRoute
  '/help/support': typeof AuthenticatedHelpSupportRoute
  '/pen/$threadId': typeof AuthenticatedPenThreadIdRoute
  '/pen/buttons': typeof AuthenticatedPenButtonsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/$issueId/flyer': typeof TableIssueIdFlyerRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/pen': typeof AuthenticatedPenIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/admin/help/$articleId': typeof AuthenticatedAdminHelpArticleIdRoute
  '/admin/journal/$postId': typeof AuthenticatedAdminJournalPostIdRoute
  '/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/help/articles/$slug': typeof AuthenticatedHelpArticlesSlugRoute
  '/help/categories/$categorySlug': typeof AuthenticatedHelpCategoriesCategorySlugRoute
  '/help/requests/$requestId': typeof AuthenticatedHelpRequestsRequestIdRoute
  '/templates/mine/$templateId': typeof AuthenticatedTemplatesMineTemplateIdRoute
  '/api/public/shelf-image/$slug': typeof ApiPublicShelfImageSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/help': typeof AuthenticatedAdminHelpIndexRoute
  '/admin/journal': typeof AuthenticatedAdminJournalIndexRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdIndexRoute
  '/help/requests': typeof AuthenticatedHelpRequestsIndexRoute
  '/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/collaborations': typeof AuthenticatedCollaborationsRoute
  '/_authenticated/cycles': typeof AuthenticatedCyclesRoute
  '/_authenticated/my-table': typeof AuthenticatedMyTableRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/api/pen': typeof ApiPenRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shelf/$slug': typeof ShelfSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/table/': typeof TableIndexRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/admin/missionpage': typeof AuthenticatedAdminMissionpageRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/releases': typeof AuthenticatedAdminReleasesRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/sitewords': typeof AuthenticatedAdminSitewordsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/tablehome': typeof AuthenticatedAdminTablehomeRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRouteWithChildren
  '/_authenticated/books/add': typeof AuthenticatedBooksAddRoute
  '/_authenticated/books/new': typeof AuthenticatedBooksNewRoute
  '/_authenticated/help/releases': typeof AuthenticatedHelpReleasesRoute
  '/_authenticated/help/support': typeof AuthenticatedHelpSupportRoute
  '/_authenticated/pen/$threadId': typeof AuthenticatedPenThreadIdRoute
  '/_authenticated/pen/buttons': typeof AuthenticatedPenButtonsRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/$issueId_/flyer': typeof TableIssueIdFlyerRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/help/': typeof AuthenticatedHelpIndexRoute
  '/_authenticated/pen/': typeof AuthenticatedPenIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/admin/help/$articleId': typeof AuthenticatedAdminHelpArticleIdRoute
  '/_authenticated/admin/journal/$postId': typeof AuthenticatedAdminJournalPostIdRoute
  '/_authenticated/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/_authenticated/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/_authenticated/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/_authenticated/help/articles/$slug': typeof AuthenticatedHelpArticlesSlugRoute
  '/_authenticated/help/categories/$categorySlug': typeof AuthenticatedHelpCategoriesCategorySlugRoute
  '/_authenticated/help/requests/$requestId': typeof AuthenticatedHelpRequestsRequestIdRoute
  '/_authenticated/templates/mine/$templateId': typeof AuthenticatedTemplatesMineTemplateIdRoute
  '/api/public/shelf-image/$slug': typeof ApiPublicShelfImageSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/help/': typeof AuthenticatedAdminHelpIndexRoute
  '/_authenticated/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
  '/_authenticated/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/_authenticated/help/requests/': typeof AuthenticatedHelpRequestsIndexRoute
  '/_authenticated/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mission'
    | '/reset-password'
    | '/admin'
    | '/collaborations'
    | '/cycles'
    | '/my-table'
    | '/submissions'
    | '/submit'
    | '/api/coach-plan'
    | '/api/pen'
    | '/journal/$slug'
    | '/shelf/$slug'
    | '/table/$issueId'
    | '/issues/'
    | '/journal/'
    | '/table/'
    | '/admin/activity'
    | '/admin/issues'
    | '/admin/missionpage'
    | '/admin/people'
    | '/admin/releases'
    | '/admin/requests'
    | '/admin/sitewords'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/tablehome'
    | '/admin/templates'
    | '/books/$bookId'
    | '/books/add'
    | '/books/new'
    | '/help/releases'
    | '/help/support'
    | '/pen/$threadId'
    | '/pen/buttons'
    | '/templates/$templateId'
    | '/table/$issueId/flyer'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/admin/'
    | '/help/'
    | '/pen/'
    | '/templates/'
    | '/admin/help/$articleId'
    | '/admin/journal/$postId'
    | '/books/$bookId/details'
    | '/books/$bookId/reflection'
    | '/books/$bookId/team'
    | '/help/articles/$slug'
    | '/help/categories/$categorySlug'
    | '/help/requests/$requestId'
    | '/templates/mine/$templateId'
    | '/api/public/shelf-image/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/help/'
    | '/admin/journal/'
    | '/books/$bookId/'
    | '/help/requests/'
    | '/books/$bookId/milestones/$milestoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mission'
    | '/reset-password'
    | '/collaborations'
    | '/cycles'
    | '/my-table'
    | '/submissions'
    | '/submit'
    | '/api/coach-plan'
    | '/api/pen'
    | '/journal/$slug'
    | '/shelf/$slug'
    | '/table/$issueId'
    | '/'
    | '/issues'
    | '/journal'
    | '/table'
    | '/admin/activity'
    | '/admin/issues'
    | '/admin/missionpage'
    | '/admin/people'
    | '/admin/releases'
    | '/admin/requests'
    | '/admin/sitewords'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/tablehome'
    | '/admin/templates'
    | '/books/add'
    | '/books/new'
    | '/help/releases'
    | '/help/support'
    | '/pen/$threadId'
    | '/pen/buttons'
    | '/templates/$templateId'
    | '/table/$issueId/flyer'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/admin'
    | '/help'
    | '/pen'
    | '/templates'
    | '/admin/help/$articleId'
    | '/admin/journal/$postId'
    | '/books/$bookId/details'
    | '/books/$bookId/reflection'
    | '/books/$bookId/team'
    | '/help/articles/$slug'
    | '/help/categories/$categorySlug'
    | '/help/requests/$requestId'
    | '/templates/mine/$templateId'
    | '/api/public/shelf-image/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/help'
    | '/admin/journal'
    | '/books/$bookId'
    | '/help/requests'
    | '/books/$bookId/milestones/$milestoneId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mission'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/collaborations'
    | '/_authenticated/cycles'
    | '/_authenticated/my-table'
    | '/_authenticated/submissions'
    | '/_authenticated/submit'
    | '/api/coach-plan'
    | '/api/pen'
    | '/journal/$slug'
    | '/shelf/$slug'
    | '/table/$issueId'
    | '/_authenticated/'
    | '/issues/'
    | '/journal/'
    | '/table/'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/issues'
    | '/_authenticated/admin/missionpage'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/releases'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/sitewords'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/tablehome'
    | '/_authenticated/admin/templates'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/books/add'
    | '/_authenticated/books/new'
    | '/_authenticated/help/releases'
    | '/_authenticated/help/support'
    | '/_authenticated/pen/$threadId'
    | '/_authenticated/pen/buttons'
    | '/_authenticated/templates/$templateId'
    | '/table/$issueId_/flyer'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/_authenticated/admin/'
    | '/_authenticated/help/'
    | '/_authenticated/pen/'
    | '/_authenticated/templates/'
    | '/_authenticated/admin/help/$articleId'
    | '/_authenticated/admin/journal/$postId'
    | '/_authenticated/books/$bookId/details'
    | '/_authenticated/books/$bookId/reflection'
    | '/_authenticated/books/$bookId/team'
    | '/_authenticated/help/articles/$slug'
    | '/_authenticated/help/categories/$categorySlug'
    | '/_authenticated/help/requests/$requestId'
    | '/_authenticated/templates/mine/$templateId'
    | '/api/public/shelf-image/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/help/'
    | '/_authenticated/admin/journal/'
    | '/_authenticated/books/$bookId/'
    | '/_authenticated/help/requests/'
    | '/_authenticated/books/$bookId/milestones/$milestoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MissionRoute: typeof MissionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCoachPlanRoute: typeof ApiCoachPlanRoute
  ApiPenRoute: typeof ApiPenRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ShelfSlugRoute: typeof ShelfSlugRoute
  TableIssueIdRoute: typeof TableIssueIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  TableIndexRoute: typeof TableIndexRoute
  TableIssueIdFlyerRoute: typeof TableIssueIdFlyerRoute
  TableAuthorsAuthorIdRoute: typeof TableAuthorsAuthorIdRoute
  TableBooksBookIdRoute: typeof TableBooksBookIdRoute
  ApiPublicShelfImageSlugRoute: typeof ApiPublicShelfImageSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collaborations': {
      id: '/_authenticated/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof AuthenticatedCollaborationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycles': {
      id: '/_authenticated/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AuthenticatedCyclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-table': {
      id: '/_authenticated/my-table'
      path: '/my-table'
      fullPath: '/my-table'
      preLoaderRoute: typeof AuthenticatedMyTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/coach-plan': {
      id: '/api/coach-plan'
      path: '/api/coach-plan'
      fullPath: '/api/coach-plan'
      preLoaderRoute: typeof ApiCoachPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pen': {
      id: '/api/pen'
      path: '/api/pen'
      fullPath: '/api/pen'
      preLoaderRoute: typeof ApiPenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/$slug': {
      id: '/shelf/$slug'
      path: '/shelf/$slug'
      fullPath: '/shelf/$slug'
      preLoaderRoute: typeof ShelfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$issueId': {
      id: '/table/$issueId'
      path: '/table/$issueId'
      fullPath: '/table/$issueId'
      preLoaderRoute: typeof TableIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/missionpage': {
      id: '/_authenticated/admin/missionpage'
      path: '/missionpage'
      fullPath: '/admin/missionpage'
      preLoaderRoute: typeof AuthenticatedAdminMissionpageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/releases': {
      id: '/_authenticated/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AuthenticatedAdminReleasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sitewords': {
      id: '/_authenticated/admin/sitewords'
      path: '/sitewords'
      fullPath: '/admin/sitewords'
      preLoaderRoute: typeof AuthenticatedAdminSitewordsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tablehome': {
      id: '/_authenticated/admin/tablehome'
      path: '/tablehome'
      fullPath: '/admin/tablehome'
      preLoaderRoute: typeof AuthenticatedAdminTablehomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/add': {
      id: '/_authenticated/books/add'
      path: '/books/add'
      fullPath: '/books/add'
      preLoaderRoute: typeof AuthenticatedBooksAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/new': {
      id: '/_authenticated/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedBooksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof AuthenticatedHelpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/releases': {
      id: '/_authenticated/help/releases'
      path: '/help/releases'
      fullPath: '/help/releases'
      preLoaderRoute: typeof AuthenticatedHelpReleasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/support': {
      id: '/_authenticated/help/support'
      path: '/help/support'
      fullPath: '/help/support'
      preLoaderRoute: typeof AuthenticatedHelpSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pen/': {
      id: '/_authenticated/pen/'
      path: '/pen'
      fullPath: '/pen/'
      preLoaderRoute: typeof AuthenticatedPenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pen/$threadId': {
      id: '/_authenticated/pen/$threadId'
      path: '/pen/$threadId'
      fullPath: '/pen/$threadId'
      preLoaderRoute: typeof AuthenticatedPenThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pen/buttons': {
      id: '/_authenticated/pen/buttons'
      path: '/pen/buttons'
      fullPath: '/pen/buttons'
      preLoaderRoute: typeof AuthenticatedPenButtonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/table/$issueId_/flyer': {
      id: '/table/$issueId_/flyer'
      path: '/table/$issueId/flyer'
      fullPath: '/table/$issueId/flyer'
      preLoaderRoute: typeof TableIssueIdFlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/authors/$authorId': {
      id: '/table/authors/$authorId'
      path: '/table/authors/$authorId'
      fullPath: '/table/authors/$authorId'
      preLoaderRoute: typeof TableAuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/books/$bookId': {
      id: '/table/books/$bookId'
      path: '/table/books/$bookId'
      fullPath: '/table/books/$bookId'
      preLoaderRoute: typeof TableBooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/help/': {
      id: '/_authenticated/admin/help/'
      path: '/help'
      fullPath: '/admin/help/'
      preLoaderRoute: typeof AuthenticatedAdminHelpIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/help/$articleId': {
      id: '/_authenticated/admin/help/$articleId'
      path: '/help/$articleId'
      fullPath: '/admin/help/$articleId'
      preLoaderRoute: typeof AuthenticatedAdminHelpArticleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal/': {
      id: '/_authenticated/admin/journal/'
      path: '/journal'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AuthenticatedAdminJournalIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal/$postId': {
      id: '/_authenticated/admin/journal/$postId'
      path: '/journal/$postId'
      fullPath: '/admin/journal/$postId'
      preLoaderRoute: typeof AuthenticatedAdminJournalPostIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/books/$bookId/': {
      id: '/_authenticated/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof AuthenticatedBooksBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/details': {
      id: '/_authenticated/books/$bookId/details'
      path: '/details'
      fullPath: '/books/$bookId/details'
      preLoaderRoute: typeof AuthenticatedBooksBookIdDetailsRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/reflection': {
      id: '/_authenticated/books/$bookId/reflection'
      path: '/reflection'
      fullPath: '/books/$bookId/reflection'
      preLoaderRoute: typeof AuthenticatedBooksBookIdReflectionRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/team': {
      id: '/_authenticated/books/$bookId/team'
      path: '/team'
      fullPath: '/books/$bookId/team'
      preLoaderRoute: typeof AuthenticatedBooksBookIdTeamRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/help/articles/$slug': {
      id: '/_authenticated/help/articles/$slug'
      path: '/help/articles/$slug'
      fullPath: '/help/articles/$slug'
      preLoaderRoute: typeof AuthenticatedHelpArticlesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/categories/$categorySlug': {
      id: '/_authenticated/help/categories/$categorySlug'
      path: '/help/categories/$categorySlug'
      fullPath: '/help/categories/$categorySlug'
      preLoaderRoute: typeof AuthenticatedHelpCategoriesCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/requests/': {
      id: '/_authenticated/help/requests/'
      path: '/help/requests'
      fullPath: '/help/requests/'
      preLoaderRoute: typeof AuthenticatedHelpRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/requests/$requestId': {
      id: '/_authenticated/help/requests/$requestId'
      path: '/help/requests/$requestId'
      fullPath: '/help/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedHelpRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/mine/$templateId': {
      id: '/_authenticated/templates/mine/$templateId'
      path: '/templates/mine/$templateId'
      fullPath: '/templates/mine/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesMineTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/shelf-image/$slug': {
      id: '/api/public/shelf-image/$slug'
      path: '/api/public/shelf-image/$slug'
      fullPath: '/api/public/shelf-image/$slug'
      preLoaderRoute: typeof ApiPublicShelfImageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/books/$bookId/milestones/$milestoneId': {
      id: '/_authenticated/books/$bookId/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/books/$bookId/milestones/$milestoneId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAdminMissionpageRoute: typeof AuthenticatedAdminMissionpageRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminReleasesRoute: typeof AuthenticatedAdminReleasesRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSitewordsRoute: typeof AuthenticatedAdminSitewordsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTablehomeRoute: typeof AuthenticatedAdminTablehomeRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminHelpArticleIdRoute: typeof AuthenticatedAdminHelpArticleIdRoute
  AuthenticatedAdminJournalPostIdRoute: typeof AuthenticatedAdminJournalPostIdRoute
  AuthenticatedAdminHelpIndexRoute: typeof AuthenticatedAdminHelpIndexRoute
  AuthenticatedAdminJournalIndexRoute: typeof AuthenticatedAdminJournalIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAdminMissionpageRoute: AuthenticatedAdminMissionpageRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminReleasesRoute: AuthenticatedAdminReleasesRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSitewordsRoute: AuthenticatedAdminSitewordsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTablehomeRoute: AuthenticatedAdminTablehomeRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminHelpArticleIdRoute: AuthenticatedAdminHelpArticleIdRoute,
  AuthenticatedAdminJournalPostIdRoute: AuthenticatedAdminJournalPostIdRoute,
  AuthenticatedAdminHelpIndexRoute: AuthenticatedAdminHelpIndexRoute,
  AuthenticatedAdminJournalIndexRoute: AuthenticatedAdminJournalIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBooksBookIdRouteChildren {
  AuthenticatedBooksBookIdDetailsRoute: typeof AuthenticatedBooksBookIdDetailsRoute
  AuthenticatedBooksBookIdReflectionRoute: typeof AuthenticatedBooksBookIdReflectionRoute
  AuthenticatedBooksBookIdTeamRoute: typeof AuthenticatedBooksBookIdTeamRoute
  AuthenticatedBooksBookIdIndexRoute: typeof AuthenticatedBooksBookIdIndexRoute
  AuthenticatedBooksBookIdMilestonesMilestoneIdRoute: typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}

const AuthenticatedBooksBookIdRouteChildren: AuthenticatedBooksBookIdRouteChildren =
  {
    AuthenticatedBooksBookIdDetailsRoute: AuthenticatedBooksBookIdDetailsRoute,
    AuthenticatedBooksBookIdReflectionRoute:
      AuthenticatedBooksBookIdReflectionRoute,
    AuthenticatedBooksBookIdTeamRoute: AuthenticatedBooksBookIdTeamRoute,
    AuthenticatedBooksBookIdIndexRoute: AuthenticatedBooksBookIdIndexRoute,
    AuthenticatedBooksBookIdMilestonesMilestoneIdRoute:
      AuthenticatedBooksBookIdMilestonesMilestoneIdRoute,
  }

const AuthenticatedBooksBookIdRouteWithChildren =
  AuthenticatedBooksBookIdRoute._addFileChildren(
    AuthenticatedBooksBookIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCollaborationsRoute: typeof AuthenticatedCollaborationsRoute
  AuthenticatedCyclesRoute: typeof AuthenticatedCyclesRoute
  AuthenticatedMyTableRoute: typeof AuthenticatedMyTableRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRouteWithChildren
  AuthenticatedBooksAddRoute: typeof AuthenticatedBooksAddRoute
  AuthenticatedBooksNewRoute: typeof AuthenticatedBooksNewRoute
  AuthenticatedHelpReleasesRoute: typeof AuthenticatedHelpReleasesRoute
  AuthenticatedHelpSupportRoute: typeof AuthenticatedHelpSupportRoute
  AuthenticatedPenThreadIdRoute: typeof AuthenticatedPenThreadIdRoute
  AuthenticatedPenButtonsRoute: typeof AuthenticatedPenButtonsRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedHelpIndexRoute: typeof AuthenticatedHelpIndexRoute
  AuthenticatedPenIndexRoute: typeof AuthenticatedPenIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedHelpArticlesSlugRoute: typeof AuthenticatedHelpArticlesSlugRoute
  AuthenticatedHelpCategoriesCategorySlugRoute: typeof AuthenticatedHelpCategoriesCategorySlugRoute
  AuthenticatedHelpRequestsRequestIdRoute: typeof AuthenticatedHelpRequestsRequestIdRoute
  AuthenticatedTemplatesMineTemplateIdRoute: typeof AuthenticatedTemplatesMineTemplateIdRoute
  AuthenticatedHelpRequestsIndexRoute: typeof AuthenticatedHelpRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCollaborationsRoute: AuthenticatedCollaborationsRoute,
  AuthenticatedCyclesRoute: AuthenticatedCyclesRoute,
  AuthenticatedMyTableRoute: AuthenticatedMyTableRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRouteWithChildren,
  AuthenticatedBooksAddRoute: AuthenticatedBooksAddRoute,
  AuthenticatedBooksNewRoute: AuthenticatedBooksNewRoute,
  AuthenticatedHelpReleasesRoute: AuthenticatedHelpReleasesRoute,
  AuthenticatedHelpSupportRoute: AuthenticatedHelpSupportRoute,
  AuthenticatedPenThreadIdRoute: AuthenticatedPenThreadIdRoute,
  AuthenticatedPenButtonsRoute: AuthenticatedPenButtonsRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedHelpIndexRoute: AuthenticatedHelpIndexRoute,
  AuthenticatedPenIndexRoute: AuthenticatedPenIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedHelpArticlesSlugRoute: AuthenticatedHelpArticlesSlugRoute,
  AuthenticatedHelpCategoriesCategorySlugRoute:
    AuthenticatedHelpCategoriesCategorySlugRoute,
  AuthenticatedHelpRequestsRequestIdRoute:
    AuthenticatedHelpRequestsRequestIdRoute,
  AuthenticatedTemplatesMineTemplateIdRoute:
    AuthenticatedTemplatesMineTemplateIdRoute,
  AuthenticatedHelpRequestsIndexRoute: AuthenticatedHelpRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MissionRoute: MissionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCoachPlanRoute: ApiCoachPlanRoute,
  ApiPenRoute: ApiPenRoute,
  JournalSlugRoute: JournalSlugRoute,
  ShelfSlugRoute: ShelfSlugRoute,
  TableIssueIdRoute: TableIssueIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  TableIndexRoute: TableIndexRoute,
  TableIssueIdFlyerRoute: TableIssueIdFlyerRoute,
  TableAuthorsAuthorIdRoute: TableAuthorsAuthorIdRoute,
  TableBooksBookIdRoute: TableBooksBookIdRoute,
  ApiPublicShelfImageSlugRoute: ApiPublicShelfImageSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
