/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as ApiCoachPlanRouteImport } from './routes/api/coach-plan'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as TableIndexRouteImport } from './routes/table.index'
import { Route as TableIssueIdRouteImport } from './routes/table.$issueId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin.issues'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin.journal'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'
import { Route as AuthenticatedBooksNewRouteImport } from './routes/_authenticated/books.new'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates.$templateId'
import { Route as TableAuthorsAuthorIdRouteImport } from './routes/table.authors.$authorId'
import { Route as TableBooksBookIdRouteImport } from './routes/table.books.$bookId'
import { Route as AuthenticatedBooksBookIdIndexRouteImport } from './routes/_authenticated/books.$bookId.index'
import { Route as AuthenticatedBooksBookIdDetailsRouteImport } from './routes/_authenticated/books.$bookId.details'
import { Route as AuthenticatedBooksBookIdReflectionRouteImport } from './routes/_authenticated/books.$bookId.reflection'
import { Route as AuthenticatedBooksBookIdTeamRouteImport } from './routes/_authenticated/books.$bookId.team'
import { Route as AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport } from './routes/_authenticated/books.$bookId.milestones.$milestoneId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCoachPlanRoute = ApiCoachPlanRouteImport.update({
  id: '/api/coach-plan',
  path: '/api/coach-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIssueIdRoute = TableIssueIdRouteImport.update({
  id: '/table/$issueId',
  path: '/table/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksNewRoute = AuthenticatedBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)
const TableAuthorsAuthorIdRoute = TableAuthorsAuthorIdRouteImport.update({
  id: '/table/authors/$authorId',
  path: '/table/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableBooksBookIdRoute = TableBooksBookIdRouteImport.update({
  id: '/table/books/$bookId',
  path: '/table/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBooksBookIdIndexRoute =
  AuthenticatedBooksBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdDetailsRoute =
  AuthenticatedBooksBookIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdReflectionRoute =
  AuthenticatedBooksBookIdReflectionRouteImport.update({
    id: '/reflection',
    path: '/reflection',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdTeamRoute =
  AuthenticatedBooksBookIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)
const AuthenticatedBooksBookIdMilestonesMilestoneIdRoute =
  AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => AuthenticatedBooksBookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/journal/': typeof JournalIndexRoute
  '/table/': typeof TableIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRouteWithChildren
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/journal': typeof JournalIndexRoute
  '/table': typeof TableIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdIndexRoute
  '/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/api/coach-plan': typeof ApiCoachPlanRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/table/$issueId': typeof TableIssueIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/table/': typeof TableIndexRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRouteWithChildren
  '/_authenticated/books/new': typeof AuthenticatedBooksNewRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/table/authors/$authorId': typeof TableAuthorsAuthorIdRoute
  '/table/books/$bookId': typeof TableBooksBookIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/books/$bookId/details': typeof AuthenticatedBooksBookIdDetailsRoute
  '/_authenticated/books/$bookId/reflection': typeof AuthenticatedBooksBookIdReflectionRoute
  '/_authenticated/books/$bookId/team': typeof AuthenticatedBooksBookIdTeamRoute
  '/_authenticated/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/_authenticated/books/$bookId/milestones/$milestoneId': typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/submissions'
    | '/submit'
    | '/templates'
    | '/api/coach-plan'
    | '/journal/$slug'
    | '/table/$issueId'
    | '/journal/'
    | '/table/'
    | '/admin/activity'
    | '/admin/issues'
    | '/admin/journal'
    | '/admin/people'
    | '/admin/submissions'
    | '/admin/templates'
    | '/books/$bookId'
    | '/books/new'
    | '/templates/$templateId'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/admin/'
    | '/books/$bookId/details'
    | '/books/$bookId/reflection'
    | '/books/$bookId/team'
    | '/books/$bookId/'
    | '/books/$bookId/milestones/$milestoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/submissions'
    | '/submit'
    | '/templates'
    | '/api/coach-plan'
    | '/journal/$slug'
    | '/table/$issueId'
    | '/'
    | '/journal'
    | '/table'
    | '/admin/activity'
    | '/admin/issues'
    | '/admin/journal'
    | '/admin/people'
    | '/admin/submissions'
    | '/admin/templates'
    | '/books/new'
    | '/templates/$templateId'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/admin'
    | '/books/$bookId/details'
    | '/books/$bookId/reflection'
    | '/books/$bookId/team'
    | '/books/$bookId'
    | '/books/$bookId/milestones/$milestoneId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/submissions'
    | '/_authenticated/submit'
    | '/_authenticated/templates'
    | '/api/coach-plan'
    | '/journal/$slug'
    | '/table/$issueId'
    | '/_authenticated/'
    | '/journal/'
    | '/table/'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/issues'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/templates'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/books/new'
    | '/_authenticated/templates/$templateId'
    | '/table/authors/$authorId'
    | '/table/books/$bookId'
    | '/_authenticated/admin/'
    | '/_authenticated/books/$bookId/details'
    | '/_authenticated/books/$bookId/reflection'
    | '/_authenticated/books/$bookId/team'
    | '/_authenticated/books/$bookId/'
    | '/_authenticated/books/$bookId/milestones/$milestoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCoachPlanRoute: typeof ApiCoachPlanRoute
  JournalSlugRoute: typeof JournalSlugRoute
  TableIssueIdRoute: typeof TableIssueIdRoute
  JournalIndexRoute: typeof JournalIndexRoute
  TableIndexRoute: typeof TableIndexRoute
  TableAuthorsAuthorIdRoute: typeof TableAuthorsAuthorIdRoute
  TableBooksBookIdRoute: typeof TableBooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/coach-plan': {
      id: '/api/coach-plan'
      path: '/api/coach-plan'
      fullPath: '/api/coach-plan'
      preLoaderRoute: typeof ApiCoachPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$issueId': {
      id: '/table/$issueId'
      path: '/table/$issueId'
      fullPath: '/table/$issueId'
      preLoaderRoute: typeof TableIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/new': {
      id: '/_authenticated/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedBooksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
    '/table/authors/$authorId': {
      id: '/table/authors/$authorId'
      path: '/table/authors/$authorId'
      fullPath: '/table/authors/$authorId'
      preLoaderRoute: typeof TableAuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/books/$bookId': {
      id: '/table/books/$bookId'
      path: '/table/books/$bookId'
      fullPath: '/table/books/$bookId'
      preLoaderRoute: typeof TableBooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/books/$bookId/': {
      id: '/_authenticated/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof AuthenticatedBooksBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/details': {
      id: '/_authenticated/books/$bookId/details'
      path: '/details'
      fullPath: '/books/$bookId/details'
      preLoaderRoute: typeof AuthenticatedBooksBookIdDetailsRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/reflection': {
      id: '/_authenticated/books/$bookId/reflection'
      path: '/reflection'
      fullPath: '/books/$bookId/reflection'
      preLoaderRoute: typeof AuthenticatedBooksBookIdReflectionRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/team': {
      id: '/_authenticated/books/$bookId/team'
      path: '/team'
      fullPath: '/books/$bookId/team'
      preLoaderRoute: typeof AuthenticatedBooksBookIdTeamRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
    '/_authenticated/books/$bookId/milestones/$milestoneId': {
      id: '/_authenticated/books/$bookId/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/books/$bookId/milestones/$milestoneId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTemplatesRouteChildren {
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
}

const AuthenticatedTemplatesRouteChildren: AuthenticatedTemplatesRouteChildren =
  {
    AuthenticatedTemplatesTemplateIdRoute:
      AuthenticatedTemplatesTemplateIdRoute,
  }

const AuthenticatedTemplatesRouteWithChildren =
  AuthenticatedTemplatesRoute._addFileChildren(
    AuthenticatedTemplatesRouteChildren,
  )

interface AuthenticatedBooksBookIdRouteChildren {
  AuthenticatedBooksBookIdDetailsRoute: typeof AuthenticatedBooksBookIdDetailsRoute
  AuthenticatedBooksBookIdReflectionRoute: typeof AuthenticatedBooksBookIdReflectionRoute
  AuthenticatedBooksBookIdTeamRoute: typeof AuthenticatedBooksBookIdTeamRoute
  AuthenticatedBooksBookIdIndexRoute: typeof AuthenticatedBooksBookIdIndexRoute
  AuthenticatedBooksBookIdMilestonesMilestoneIdRoute: typeof AuthenticatedBooksBookIdMilestonesMilestoneIdRoute
}

const AuthenticatedBooksBookIdRouteChildren: AuthenticatedBooksBookIdRouteChildren =
  {
    AuthenticatedBooksBookIdDetailsRoute: AuthenticatedBooksBookIdDetailsRoute,
    AuthenticatedBooksBookIdReflectionRoute:
      AuthenticatedBooksBookIdReflectionRoute,
    AuthenticatedBooksBookIdTeamRoute: AuthenticatedBooksBookIdTeamRoute,
    AuthenticatedBooksBookIdIndexRoute: AuthenticatedBooksBookIdIndexRoute,
    AuthenticatedBooksBookIdMilestonesMilestoneIdRoute:
      AuthenticatedBooksBookIdMilestonesMilestoneIdRoute,
  }

const AuthenticatedBooksBookIdRouteWithChildren =
  AuthenticatedBooksBookIdRoute._addFileChildren(
    AuthenticatedBooksBookIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRouteWithChildren
  AuthenticatedBooksNewRoute: typeof AuthenticatedBooksNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRouteWithChildren,
  AuthenticatedBooksNewRoute: AuthenticatedBooksNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCoachPlanRoute: ApiCoachPlanRoute,
  JournalSlugRoute: JournalSlugRoute,
  TableIssueIdRoute: TableIssueIdRoute,
  JournalIndexRoute: JournalIndexRoute,
  TableIndexRoute: TableIndexRoute,
  TableAuthorsAuthorIdRoute: TableAuthorsAuthorIdRoute,
  TableBooksBookIdRoute: TableBooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
